language: python
dist: xenial
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install -r requirements.test.txt
  - pip install nose
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_address --ignore F999
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok_address/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok_address

after_success:
  coveralls
